version: 1.2.1-win-{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: x64
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CppCompilerAndLinker: clang
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: 'C:\projects\fata-morgana\packages'
cache:
  - 'packages'
before_build:
- pwsh: >-
    Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/78836c06-166d-4145-ae7b-da5693e36665/431a2fd34af25742527bc5cafe4d8fae/dotnet-sdk-3.0.100-preview5-011568-win-x64.zip" -OutFile "dotnet-sdk-3.0.100-preview5-011568-win-x64.zip"

    Expand-Archive "dotnet-sdk-3.0.100-preview5-011568-win-x64.zip" -DestinationPath "dotnet"

    Set-Item Env:Path "C:\projects\fata-morgana\dotnet;$Env:Path"
build_script:
- pwsh: .\dotnet\dotnet.exe publish -c Release -r win-x64 -o dist --version-suffix "win-$APPVEYOR_BUILD_NUMBER"
artifacts:
- path: 'dist\'
