version: 1.0.0-win-{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: x64
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CppCompilerAndLinker: clang
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: 'C:\projects\fata-morgana\packages'
cache:
  - 'packages'
before_build:
- pwsh: >-
    Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/a3fe6da8-1ec8-48e5-b93d-cbf6cbe4e1ad/b4c6e212cda446fcc6c305296130e76b/dotnet-sdk-3.0.100-preview4-011223-win-x64.zip" -OutFile "dotnet-sdk-3.0.100-preview4-011223-win-x64.zip"
    Expand-Archive "dotnet-sdk-3.0.100-preview4-011223-win-x64.zip" -DestinationPath "dotnet"
    Set-Item Env:Path "C:\projects\fata-morgana\dotnet;$Env:Path"
build_script:
- pwsh: dotnet publish -c Release -r win-x64 -o dist
artifacts:
- path: 'dist\'
