version: 2

jobs:
  build:
    docker:
      - image: 346design/dotnet.corert
        environment:
          CppCompilerAndLinker: clang
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          NUGET_XMLDOC_MODE: skip
    steps:
      - checkout
      - run:
          name: Install latest .NET Core SDK manually
          command: |
            wget https://download.visualstudio.microsoft.com/download/pr/7e4b403c-34b3-4b3e-807c-d064a7857fe8/95c738f08e163f27867e38c602a433a1/dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz
            mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.0.100-preview5-011568-linux-x64.tar.gz -C $HOME/dotnet
            export DOTNET_ROOT="$HOME/dotnet"
            export PATH="$DOTNET_PATH:$PATH"
      - run:
          name: Checking Hashes
          command: |
            dotnet --version > DOTNET_SDK_VERSION
            zsh -c 'grep PackageReference **/*.csproj' > NUGET_PACKAGE_REFERENCES
      - restore_cache:
          keys:
            - nuget-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-sdk-{{ checksum "DOTNET_SDK_VERSION" }}-nuget-{{ checksum "NUGET_PACKAGE_REFERENCES" }}-
            - nuget-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-sdk-{{ checksum "DOTNET_SDK_VERSION" }}-
            - nuget-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-
            - nuget-v1-arch-{{ arch }}-env-
            - nuget-v1-
      - run:
          name: Restoring NuGet Packages
          command: |
            dotnet restore
      - run:
          name: Building Project
          command: |
            dotnet publish -r linux-x64 -c Release -o dist --version-suffix "linux-$CIRCLE_BUILD_NUM"
            tar -jcvf linux-x64.tar.bz2 dist
      - run:
          name: Checking Hashes
          command: |
            ls -alR ~/.nuget/packages > NUGET_PACKAGES
      - save_cache:
          key: nuget-v1-arch-{{ arch }}-env-{{ .Environment.variableName }}-sdk-{{ checksum "DOTNET_SDK_VERSION" }}-nuget-{{ checksum "NUGET_PACKAGE_REFERENCES" }}-{{ checksum "NUGET_PACKAGES" }}
          paths:
            - ~/.nuget/packages
      - store_artifacts:
          path: linux-x64.tar.bz2
workflows:
  version: 2
  build:
    jobs:
      - build
