name: build
on:
  push:
    branches:
    - master
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime-identifier: win-x64
            dotnet-version: 3.1.301
            version-suffix: gha-win-x64-${{ github.run_number }}
          - os: macos-latest
            runtime-identifier: osx-x64
            dotnet-version: 3.1.301
            version-suffix: gha-osx-x64-${{ github.run_number }}
          - os: ubuntu-latest
            runtime-identifier: linux-x64
            dotnet-version: 3.1.301
            version-suffix: gha-linux-x64-${{ github.run_number }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - shell: bash
      env:
        P: ${{ secrets.P }}
        R: ${{ matrix.runtime-identifier }}
        S: ${{ matrix.version-suffix }}
      run: |
        if $(dotnet publish -r "$R" -c Release -o dist --version-suffix "$S")
          then
            :
          else
            touch .no-rtr
            dotnet publish -r "$R" -c Release -o dist --version-suffix "$S"
        fi
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -rP "${{ secrets.P }}" dist.zip dist
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.version-suffix }}
        path: dist.zip
